# Generated by Django 4.1.6 on 2023-02-14 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("age", models.CharField(max_length=30)),
                ("phone", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "bio",
                    models.TextField(blank=True, max_length=256, verbose_name="bio"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="/pic.jpg", null=True, upload_to=""
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
