# Generated by Django 4.1.6 on 2023-02-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsForms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='img',
        ),
        migrations.AlterField(
            model_name='pet',
            name='date',
            field=models.DateField(),
        ),
    ]
