# Generated by Django 4.1.6 on 2023-02-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsForms', '0003_alter_pet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='date',
            field=models.DateTimeField(max_length=50),
        ),
    ]
