# Generated by Django 4.1.6 on 2023-02-21 16:29
# Generated by Django 4.1.6 on 2023-02-16 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_img', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
