### Root api
GET http://localhost:4000/


### Endpoint blog

    ### ==== Call all blogs ===== ####
GET http://localhost:4000/api/blog


### ==== Call all blogs ===== ####
GET http://localhost:4000/api/blog/img

### ==== Blog by id ===== ####
GET http://localhost:4000/api/blog/65466fc28d72e320b376fa7b

### ==== Create blog ===== ####
POST http://localhost:4000/api/blog
Content-Type: application/json

{
    "title": "blog sin problemas",    
    "sub_title": "mi primer juego",
    "description": "If you encounter game crashes, please try updating your graphics card driver. We are sorry to inform you that AMD graphics cards and some earlier released NVIDIA graphics cards may experience crashes when starting the game. You can try updating your graphics card driver to resolve this issue.",
    "short_description": "prueba short",
    "image_url": "https://media.rawg.io/media/screenshots/d75/d75bf15ab007368615b155ab1f93b002.jpg"   
}



### Endpoint forms
GET http://localhost:4000/api/forms

### Endpoint forms
GET http://localhost:4000/api/tag

### Endpoint forms
GET http://localhost:4000/api/category


### Endpoint forms
GET http://localhost:4000/api/forms