### Root api
GET http://localhost:4000/


### Endpoint blog
GET http://localhost:4000/api/blog


### Endpoint forms
GET http://localhost:4000/api/forms

### Endpoint forms
GET http://localhost:4000/api/tag

### Endpoint forms
GET http://localhost:4000/api/category


### Endpoint forms
GET http://localhost:4000/api/forms