### Root api
GET http://localhost:4000/


### GetAll BLOG
GET http://localhost:4000/api/blog
### ById BLOG
GET http://localhost:4000/api/blog/65584935fcd07652c3e02fae   

### create BLOG
POST http://localhost:4000/api/blog
Content-Type: application/json

{
    "title": "Nostrum numquam debitis ea.",
    "sub_title": "Velit id ut minima.",   
    "description": "Ut beatae qui. Explicabo explicabo et possimus illum officia reiciendis non ipsa laborum. Vel molestiae natus. Tempora placeat unde. Velit provident et incidunt sunt debitis. Qui ut similique.\n \rIpsum ullam omnis sit qui. Optio nam possimus excepturi cupiditate ipsum excepturi ut deserunt fugiat. Eos debitis qui quia voluptatem deserunt blanditiis adipisci id. Dolores qui perspiciatis rerum aut temporibus perferendis cumque et.\n \rVero qui omnis. Magnam non reprehenderit sequi praesentium. Asperiores nobis et blanditiis eum eveniet quis nihil distinctio.",
    "short_description": "Rerum repellat nemo quod fugiat reiciendis vel. Facere architecto omnis reprehenderit laudantium optio dolorem unde. Tempore earum et sed et nemo consectetur voluptatem. Repellat aperiam est amet aspernatur nesciunt sit impedit hic. Aliquid aut rerum aut laborum harum itaque nulla. Voluptas quaerat iste eos saepe reprehenderit.",
    "image_url": "https://media.rawg.io/media/screenshots/d75/d75bf15ab007368615b155ab1f93b002.jpg"
    
}

### update  BLOG
PATCH http://localhost:4000/api/blog/65584935fcd07652c3e02fae
Content-Type: application/json

{
    "title": "cambio con imagen.",    
    "sub_title": "cambiando imagen",
    "description": "pequeño",
    "short_description": "ingresando un nuevo description",
     "image_url": "https://media.rawg.io/media/screenshots/c10/c100f84cb626cbc20752dc7a01c5934b.jpg",
    "status": false
    
}

### delete BLOG
DELETE  http://localhost:4000/api/blog/65584935fcd07652c3e02fae 


### GetAll FORM
GET http://localhost:8000/api/v1/form
### ById FORM
GET http://localhost:4000/api/form/65584935fcd07652c3e02fae   

### PET LOST FORM
POST http://localhost:4000/api/form/lost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzMzYzQ3NGNiMWExZDQ2YWQxNjc1OCIsImFsaWFzIjoidGVzdGluZyIsInJvbCI6IjY1NjJhMzk0NDI0ZGE5OTVhNTBiNWE1MSIsImlhdCI6MTcwMjk1NTUzMSwiZXhwIjoxNzAzMDQxOTMxfQ.z3b1agbArkNmGtVRK6-iQby8-XucedJd4SyCCFWQhRo

{
	"name": "pet2",
	"color": "yellow",
	"size": "SMALL",
	"city": "city",
	"address": "adreess",
	"contact": "123456789",
	"loss_date": "2023-11-09T12:34:56.789Z",
	"image_url": "https://cdn.discordapp.com/attachments/952030310713946172/1112498601881518100/image.png",
	"description": "pet",
	"type": "CAT",
	"type_search": "LOST"
}

### PET FOUND FORM
POST http://localhost:4000/api/form/found
Content-Type: application/json
{	
	"color": "black",
	"size": "SMALL",
	"city": "smallville",
	"address": "san andres",
	"contact": "(504) 641-2564",
	"loss_date": "2023-11-09T12:34:56.789Z",
	"image_url": "https://cdn.discordapp.com/attachments/952030310713946172/1112498601881518100/image.png",
	"description": "mascota encontrada",
	"type": "CAT",
    "type_search": "FOUND"
    
}


### update  FORM
PATCH http://localhost:4000/api/form/65584935fcd07652c3e02fae
Content-Type: application/json

{
    "name": "pet2",
	"color": "yellow",
	"size": "SMALL",
	"city": "city",
	"address": "adreess",
	"contact": "123456789",
	"loss_date": "2023-11-09T12:34:56.789Z",
	"image_url": "https://cdn.discordapp.com/attachments/952030310713946172/1112498601881518100/image.png",
	"description": "pet",
	"type": "CAT",
    "status": false
}


### Endpoint AUTH CONNECTION

## Login AUTH
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{    
    "email": "test1@gmail.com",    
    "password": "password1A@"    
}

### Logout AUTH
POST http://localhost:8000/api/v1/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzMzYzQ3NGNiMWExZDQ2YWQxNjc1OCIsImFsaWFzIjoidGVzdGluZyIsImVtYWlsIjoidGVzdDFAZ21haWwuY29tIiwicm9sIjoiNjU2MmEzOTQ0MjRkYTk5NWE1MGI1YTUxIiwiaWF0IjoxNzA0ODYxMjU3LCJleHAiOjE3MDQ5NDc2NTd9.4Z21h_5BGhFxQbRlDYpTC4v4Qs9NAVPPJzdae043oqI

### register AUTH
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "first_name": "userbrevo",
  "last_name": "apellidotest",
  "phone": "123456789",
  "email": "@gmail.com",
  "password": "password1A@",
  "alias": "testing"
}

### reset-password AUTH
POST http://localhost:4000/api/auth/656296e9cfb5ee8c58647bd9/reset-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NzMzYzQ3NGNiMWExZDQ2YWQxNjc1OCIsImFsaWFzIjoidGVzdGluZyIsImVtYWlsIjoidGVzdDFAZ21haWwuY29tIiwicm9sIjoiNjU2MmEzOTQ0MjRkYTk5NWE1MGI1YTUxIiwiaWF0IjoxNzA0ODYxMjU3LCJleHAiOjE3MDQ5NDc2NTd9.4Z21h_5BGhFxQbRlDYpTC4v4Qs9NAVPPJzdae043oqI

{
    
    "oldpassword": "password1A@",
    "newpassword": "passwordkj1A@"
}


### Endpoint USERS
GET http://localhost:4000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NjJhMzk2NDI0ZGE5OTVhNTBiNWE1YSIsImFsaWFzIjoic3VwZXJtYW4iLCJyb2wiOiI2NTYyYTM5NDQyNGRhOTk1YTUwYjVhNGUiLCJpYXQiOjE3MDA5NzYxODAsImV4cCI6MTcwMTA2MjU4MH0.TRYhDKbB8f3Vme3ooK72CZzKi1f8Qs8KVlffV22RzTQ


### getById  USER
GET http://localhost:4000/api/user/6562d742a54aca1ae1408f5f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NjJhMzk2NDI0ZGE5OTVhNTBiNWE1YSIsImFsaWFzIjoic3VwZXJtYW4iLCJyb2wiOiI2NTYyYTM5NDQyNGRhOTk1YTUwYjVhNGUiLCJpYXQiOjE3MDA5NzYxODAsImV4cCI6MTcwMTA2MjU4MH0.TRYhDKbB8f3Vme3ooK72CZzKi1f8Qs8KVlffV22RzTQ

### delete logic USER
DELETE http://localhost:4000/api/user/6562bff7e1ec086ac3f8e537/logic
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NjJhMzk2NDI0ZGE5OTVhNTBiNWE1YSIsImFsaWFzIjoic3VwZXJtYW4iLCJyb2wiOiI2NTYyYTM5NDQyNGRhOTk1YTUwYjVhNGUiLCJpYXQiOjE3MDA5NzYxODAsImV4cCI6MTcwMTA2MjU4MH0.TRYhDKbB8f3Vme3ooK72CZzKi1f8Qs8KVlffV22RzTQ

### delete erased USER
DELETE http://localhost:4000/api/user/6562bff7e1ec086ac3f8e537/logic
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NjJhMzk2NDI0ZGE5OTVhNTBiNWE1YSIsImFsaWFzIjoic3VwZXJtYW4iLCJyb2wiOiI2NTYyYTM5NDQyNGRhOTk1YTUwYjVhNGUiLCJpYXQiOjE3MDA5NjM0NTIsImV4cCI6MTcwMTA0OTg1Mn0.4fhf-ujumz9RDpKrmnQNoZCxhyCvmE3meGAZA5Lqc00

