version: "3.9"
services:
    backendtest:
        container_name: backendtest
        build: .
        ports:
            - "80:80"
        depends_on:
            - db
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
    db:
        container_name: db
        ports:
            - "3306:3306"
        image: mariadb:10.11.2
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=dogs
        volumes:
            - maria-data:/var/lib/mysql
volumes:
    maria-data:
        name: maria-data
